### ISSUE TITLE
Compatible with karma-jasmine-jquery?

### ISSUE THREAD

**Issue by ashawley** [pvdlg/karma-jasmine-jquery#82]
I have used [karma-jasmine-jquery](https://www.npmjs.com/package/karma-jasmine-jquery) v0.1.1 for a while.  Is this package, [@metahub/karma-jasmine-jquery](https://www.npmjs.com/package/@metahub/karma-jasmine-jquery), a drop-in replacement for karma-jasmine-jquery v01.1.1?

I didn't see anything about this mentioned in the readme file.

**Comment by pvdlg** [comment]
Yes, I created it because `karma-jasmine-jquery` doesn't seems to be maintained.

**Comment by ashawley** [comment]
That is fantastic, and thank you!

So is this a rewrite, or a fork of the original?

**Comment by pvdlg** [comment]
Neither, it's a different project that achieve the same functionality.
