### ISSUE TITLE
Add link to npmjs

### ISSUE THREAD

**Issue by ashawley** [pvdlg/karma-jasmine-jquery#85]
Maybe make the [link](https://www.npmjs.com/package/@metahub/karma-jasmine-jquery) to npmjs.com as the "web site" to this GitHub project?

**Comment by pvdlg** [comment]
What's the point? It would display the same README as the GitHub repo and would confuse people into thinking there is an actual website for the project.

**Comment by ashawley** [comment]
The npmjs.com site shows a little more information about the package than what is on the README and in the Github repo.  I find it useful to cross-check the package information on npmjs.com, but that's me I guess.

**Comment by pvdlg** [comment]
See https://github.com/pvdlg/karma-jasmine-jquery/pull/86#issuecomment-409431544
